#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED


#define NB_LINE 20
#define NB_COL 3

#define GRID_ELEMENT_CAR 1
#define GRID_ELEMENT_BUS 3
#define GRID_ELEMENT_EXPLOSION 4
#define GRID_ELEMENT_EMPTY 0
#define GRID_ELEMENT_SHOOT 2


#endif // CONSTANTS_H_INCLUDED
